osx_image: xcode12.5
language: swift
os: osx


# project information
xcode_workspace: BlockIDTestApp.xcworkspace
xcode_scheme: BlockIDTestApp
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
